### ISSUE TITLE
Windows 10 theme doesn't change automatically on latest Fast ring insider build

### ISSUE THREAD

**Issue by VincentJoshuaET** [t1m0thyj/WinDynamicDesktop#100]
I enabled More options > Change Windows 10 theme color and it does not work.
 - Windows version 10 1903 18334.1
 - WinDynamicDesktop version 3.0.0
- Installation source Microsoft Store

**Comment by leogcry22** [comment]
same here

**Comment by FantasiaChan** [comment]
Have you tried using The github version? I don't know how, but it often helps.

I have it working, but after turn off did not return to the theme color back
(Yandex.Translate)

**Comment by t1m0thyj** [comment]
Since currently I don't have access to the Insider edition of Windows 10, could you try opening the Registry Editor, navigate to `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize` (you can paste the path in at the top of the window), and manually toggle these 2 values between 0 and 1 (create them if either one doesn't exist).

* `AppsUseLightTheme`
* `SystemUsesLightTheme`

0 means dark theme and 1 means light, you should see it change right away if you have an app open that gets themed like Windows 10 Settings. Changing these registry values is what the app should be doing under the covers.

**Comment by khuongduybui** [comment]
Using latest version of WDD from the Store and Windows 1903 Fast Ring (build 18898).
When I modify the 2 keys above manually, app theme and window theme does change.
However, I don't see the app changing these values at all. I even tried running it as admin and got no change.

**Comment by t1m0thyj** [comment]
Since the May update that has a new light theme was released, I investigated this and discovered this feature seems to work fine in the desktop version but not the Microsoft Store version. It appears that Store apps are not allowed to edit the registry, which unfortunately makes this feature not possible in the Store version unless I can find a workaround.

**Comment by t1m0thyj** [comment]
Since Microsoft Store apps are not allowed to modify system registry entries, unfortunately I had to remove this feature from the Store app because it couldn't work there. This feature is still available in the desktop version available from GitHub.

**Comment by stephtr** [comment]
> Since Microsoft Store apps are not allowed to modify system registry entries, unfortunately I had to remove this feature from the Store app because it couldn't work there. This feature is still available in the desktop version available from GitHub.

I have made a [small app](https://github.com/stephtr/BrightnessSwitch) for switching between dark and light theme depending on the light sensor (go outdoors -> light theme, return indoors -> dark theme). I also published it to the Microsoft store; the way I overcame that limitation is by simply [calling the `reg` command](https://github.com/stephtr/BrightnessSwitch/blob/82b8979ea9bc1ff3e84bdd5adcb26d2ad0bc50a0/BrightnessSwitch/ThemeUtils.cs#L14) for making system-wide changes to the registry.

**Comment by t1m0thyj** [comment]
@stephtr I've tried calling the reg command identical to how you did it and it does indeed work in a UWP app. However, it also causes a terminal window to briefly flicker on my machine, even when the "CreateNoWindow" flag is used.

**Comment by stephtr** [comment]
Ah thanks, seems like one has to use `WindowStyle = ProcessWindowStyle.Hidden` for console applications; I never noticed/tested the terminal window.

**Comment by t1m0thyj** [comment]
Also tried that, unfortunately with `WindowStyle = ProcessWindowStyle.Hidden` I still see a terminal window flicker.

**Comment by stephtr** [comment]
Maybe you also have to set `UseShellExecute` to `false`. Apparently that's `true` by default for .NET < 5 and `false` for .NET Core.
